version: '3'

services:
  api:
    hostname: sample-api
    image: "vad1mo/hello-world-rest"
    ports:
      - 5050:5050
  nginx:
    image: "nginx:1.19.10"
    ports:
      - 8080:80
      - 8008:8008
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/sample.conf:/etc/nginx/conf.d/sample.conf
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/oauth2.js:/etc/nginx/oauth2.js
  keycloak:
    hostname: keycloak
    image: "jboss/keycloak:12.0.4"
    ports:
      - 8000:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
