version: '3'

services:
  nginx:
    image: "nginx:1.19.10"
    ports:
      - 8080:80
      - 8008:8008
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/sample.conf:/etc/nginx/conf.d/sample.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/oauth2.js:/etc/nginx/oauth2.js
    networks:
      - default

networks:
  default:
    name: keycloak-nginx
