version: '3'

services:
  api:
    image: "vad1mo/hello-world-rest"
    ports:
      - 5050:5050
  nginx:
    image: "nginx:1.19.10"
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
  keycloak:
    image: "jboss/keycloak:12.0.4"
    ports:
      - 8000:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
