version: '3'

services:
  api:
    hostname: sample-api
    image: "vad1mo/hello-world-rest"
    ports:
      - 5050:5050
    networks:
      - default
  keycloak:
    hostname: keycloak
    image: "jboss/keycloak:12.0.4"
    ports:
      - 8000:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    networks:
      - default

networks:
  default:
    name: keycloak-nginx
